### ISSUE TITLE
using GDB with VScode sometimes can generate System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jx2014** [PowerShell/PSReadLine#3155]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new      
-----------------------------------------------------------------------Last 200 Keys:
 s y s 6 4 / m i n g w 6 4 / b i n / g d b . e x e ' Space ' - - i n t 
e r p r e t e r = m i ' Space Enter
 UpArrow UpArrow DownArrow DownArrow DownArrow c d Space K Tab Enter   
 c d Space . . Enter
 \ Backspace . \ K Tab c h 5 e Backspace _ e Tab Tab Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow 1 Backspace Enter
 UpArrow Enter
 UpArrow Enter
 Space & Space ' c : \ U s e r s \ s t u d y p c \ . v s c o d e \ e x 
t e n s i o n s \ m s - v s c o d e . c p p t o o l s - 1 . 8 . 0 - i n s i d e r s 2 \ d e b u g A d a p t e r s \ b i n \ W i n d o w s     

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
'--stdin=Microsoft-MIEngine-In-ev0aiok3.dss' '--stdout=Microsoft-MIEngine-Out-u0yfj3vf.4n3' '--stderr=Microsoft-MIEngine-Error-jadla41w.51b' '--pid=Microsoft-MIEnt-MIEngine-Pid-jjzibgv5.nv5' '--dbgExe=c:/msys64/mingw64/bin/gdb.exe' '--interpreter=mi'




>>
>>
>>
>>
>>  & 'c:\Users\studypc\.vscode\extensions\ms-vscode.cpptools-1.8.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-d3tannsc.q0l' '--stdout=Microsoft-MIEngine-Out-xefhp52s.tua' '--stderr=Microsoft-MIEngine-Error-zs124yc1.clu' '--pid=Microsoft-MIEngine-Pid-nneyebh1.lht' '--dbgExe=c:/msys64/mingw64/bin/gdb.exe' '--interpreter=mi'                                                                                                      annsc.
>>                                                                                                                                                          :/msys
>>  & 'c:\Users\studypc\.vscode\extensions\ms-vscode.cpptools-1.8.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-4rxgjyaq.tzx' '--stdout=Microsoft-MIEngine-Out-01xpxdpj.1ht' '--stderr=Microsoft-MIEngine-Error-mqmq2gf5.w32' '--pid=Microsoft-MIEngine-Pid-vapguunx.zyv' '--dbgExe=c:/msys64/mingw64/bin/gdb.exe' '--interpreter=mi' 
>>
>>
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

This problem does not occur 100%. Most likely will occur 10% of the time.
Once I get a failure build with error message above, I would have to exit and relaunch vscode.
The same code can be recompiled over and over without issues at times. 

### **Visual Code Studio**
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

### .vscode configuration
**launch.json****
```
{
            "name": "(gdb) Build & Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": true,
            "MIMode": "gdb",
            "miDebuggerPath": "c:/msys64/mingw64/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe build active file"
        },
```

**tasks.json**

```
{
			"type": "cppbuild",
			"label": "C/C++: gcc.exe build active file",
			"command": "c:/msys64/mingw64/bin/gcc.exe",
			"args": [
				"-g",				
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe",
				"-Wall",
				"-Werror",
				"-std=c11"
			],
			"options": {
				"cwd": "${fileDirname}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"detail": "compiler:  C:/msys64/mingw64/bin/gcc.exe",
			"dependsOn": ["CLEAN"]
		},
```

### Expected behavior

Failure to compile 

### Actual behavior

Can compile
