### ISSUE TITLE
VSCode testing Terminal crashing (Possibly after updating a Python Extension. Exact one unknown.)

### ISSUE THREAD

**Issue by Destroyer1724** [PowerShell/PSReadLine#3981]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 192 Keys:
 & Space " c : / ********** / D o c u m e n t s / J a v a S c r i p t Space s t u f f / c o m p l e t e - j a v a s c r i p t - c o u r s e - m a s t e r / 1 8 - f o r k i f y / f i n a l / . v e n v / S c r i p t s / p y t h o n . e x e " Space " c : / ********** / D e s k t o p / P y t h o n Space S t u f f / P y t h o n Space C o u r s e / H e l l o W o r l d . p y " Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than 
the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

File path in Exception report edited to remove PC and user name. The rest is exact.

Previous "fix" was close VSCode, wait and re-open but that's not working anymore

### Environment data

```console
PS Version: 5.1.19041.4170
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 98
BufferHeight: 44
```

### Steps to reproduce

Sorry for the text wall below. First time reporting an official bug and thought too much info is better than too little.
# Extensions used when crash happened
```
Name				| Version	| Creator

Auto Close Tag 			| v0.5.15 	| Jun Han
Auto Rename Tag 		| v0.1.10 	| Jun Han
autopep8 			| v2023.8.0 	| Microsoft
Color Highlight 		| v2.8.0 	| Sergi N
Darcula PyCharm Theme 		| v1.0.0 	| garytyler
ESLint 				| v2.4.4 	| Microsoft
Image preview 			| v0.30.0 	| Kiss Tamás
IntelliJ IDEA Keybindings 	| v1.6.0 	| Keisuke Kato
isort 				| v2023.10.1 	| Microsoft
Jupyter 			| v2024.2.0 	| Microsoft
Jupyter Cell Tags 		| v0.1.8 	| Microsoft
Jupyter Keymap 			| v1.1.2 	| Microsoft
Jupyter Notebook Renderers 	| v1.0.17 	| Microsoft
Jupyter Slide Show 		| v0.1.5 	| Microsoft
Live Server 			| v5.7.9 	| Ritwick Dey
MagicPython 			| v1.1.0 	| MagicStack Inc
Monokai Pro 			| v1.2.2 	| monokai
Prettier - Code formatter 	| v10.4.0 	| Prettier
Pylance 			| v2024.3.2 	| Microsoft
Python 				| v2024.2.1 	| Microsoft
Python Debugger 		| v2024.2.0 	| Microsoft
Python Envy 			| v0.1.5 	| Robert Dargavel Smith
TODO Highlight 			| v1.0.5 	| Wayou Liu
```
Opening the python file with code below and clicking the run play button in VSCode should be enough.
# Code
```
# #TODO
# print("Hello World!")


# #TODO String manipulation
# greeting = "Hello"
# name = input("Please enter your name: ")
# print(greeting+" "+name+"!")

# print('End ',"of ",'test')


# #TODO
# a = 12
# b = 3

# print(a+b , a-b , a*b , a/b , a//b , a%b)   # 15 , 9 , 36 , 4.0 , 4 , 0


# #TODO
# letters = "abcdefghijklmnopqrstuvwxyz"
# i = 0
# for x in letters:
#     print(i,": ",x)
#     i = i+1
# print()
# print(letters[16:13:-1])
# print()
# print(letters[4::-1])
# print()
# print(letters[len(letters):len(letters)-9:-1]," (",len(letters[len(letters):len(letters)-9:-1]),")",)
# print(letters[:-9:-1])

# # slicing with [::-1] is rreversing
# # slicing with [-X:] is getting the last X parts
# # slicing with [:X] is getting the first X parts

# print("Hell" in "Hello")

# age = 24
# print("My age is " + str(age) + " years")
# print("My age is {0} years".format(age))
# print("Hi. I'm {0} and am {1} years old".format("Bob",24))
# template1 = "{0} squared is {1} and {0} cubed is {2}"
# for i in range(1, 6):
#     print(template1.format(i, i**2, i**3))
# print()
# template2 = "{0:2} squared is {1:3} and {0:2} cubed is {2:4}"
# for i in range(1, 6):
#     print(template2.format(i, i**2, i**3))
# print()
# template3 = "{0:>2} squared is {1:^3} and {0:<2} cubed is {2:^4}"
# for i in range(1, 6):
#     print(template3.format(i, i**2, i**3))
# print()

# print("Pi is aproximately {0:<12} (Regular formatting to 12 spaces)".format(22/7))
# print("Pi is aproximately {0:<12f} (Formatting to 12 spaces WITH floating decimal)".format(22/7))
# print("Pi is aproximately {0:<12.50f} (Formatting to 12 spaces with floating Decimal TAKING PRIORITY)".format(22/7))
# print("Pi is aproximately {0:<52.50f} (Formatting to 52 spaces with floating Decimal TAKING PRIORITY)".format(22/7))
# print("Pi is aproximately {0:<62.50f} (Formatting to 62 spaces with floating Decimal TAKING PRIORITY)".format(22/7))
# print("Pi is aproximately {0:<72.50f} (Formatting to 72 spaces with floating Decimal TAKING PRIORITY)".format(22/7))

# end_of_loop = 12
# for i in range(1,end_of_loop+1):
#     print(i)


# #TODO Principles of Guessing Game
# answer = 5
# print("Please guess a number between 1 and 10: ")
# guess = int(input())

# if guess != answer:
#     if guess < answer:
#         print("Please guess higher.")
#     else:   # guess must be higher than answer
#         print("Please guess lower.")
#     guess = int(input())
#     if guess == answer:
#         print("Well done, you guessed it.")
#     else:
#         print("Sorry, you have not guessed correctly.")
# else:
#     print("You got it first time.")

# if guess == answer:
#     print("You got it first time.")
# else:
#     if guess < answer:
#         print("Please guess higher.")
#     else:   # guess must be higher than answer
#         print("Please guess lower.")
#     guess = int(input())
#     if guess == answer:
#         print("Well done, you guessed it.")
#     else:
#         print("Sorry, you have not guessed correctly.")


# name = input("What is your name? ")
# age = int(input("How old are you? "))

# if 18 <= age < 31:
#     print("You can go on the holiday {}".format(name))
# else:
#     print("Sorry {} you can't go on the holiday since you are {}".format(name,age))

# for i in range(1,12+1):
#     for j in range(1,12+1):
#         print("| {0:^2} x {1:^2} = {2:^3} |".format(i,j,i*j))
#     print("-"*len("| 12 x 12 = 144 |"))


# # TODO Guessing Game (Player guesses)
# import random
# highest = random.randint(10,100)
# answer = random.randint(1,highest)
# # print(answer)
# guess = None
# num_guesses = 1
# guess = int(input("Please guess a number between 1 and {}: ".format(highest)))
# if guess == answer:
#     print("You got it first time.")
# else:
#     while guess != answer:
#         if guess == 0:
#             print("Ending game ...")
#             break
#         if guess < answer:
#             guess = int(input("Please guess higher. "))
#         else:   # guess must be higher than answer
#             guess = int(input("Please guess lower. " ))
#         num_guesses += 1
#     if guess == answer:
#         print("Well done, you guessed it in {} tries.".format(num_guesses))


# # TODO Reverse Guessing Game (Program Guesses)
# low = 1
# high = 1000

# print("Please think of a number between {} and {}: ".format(low,high))
# input("Press ENTER to start" )

# guess = None
# num_guesses = 1
# while low != high:
#     # print("\tGuessing in the range of {} to {}: ".format(low, high))
#     guess = low + (high-low) // 2
#     high_low = input("My guess is {}. Should I go higher, lower or am I correct? Enter 'h', 'l' or 'c': ".format(guess)).casefold()

#     if high_low == 'h': # we set the case of the input to lower
#         # guess higher The low end of the range becomes 1 greater than the guess
#         low = guess + 1
#     elif high_low == 'l': # we set the case of the input to lower
#         # guess lower The high end of the range becomes 1 less than the guess
#         high = guess - 1
#     elif high_low == 'c': # we set the case of the input to lower
#         print("We got it. Only took {} guesses. ".format(num_guesses))
#         break
#     else:
#         print("Please enter 'h', 'l' or 'c'.: ")
# #    num_guesses = num_guesses + 1
#     num_guesses += 1
# else:
#     print("You thought of {} for certain. We got it in {}. ".format(low,num_guesses))


# #TODO Choosing options fropm Lists
# options = ["1.\tLearn Python","2.\tLearn Java","3.\tGo swimming","4.\tHave dinner","5.\tGo to bed"]
# options.append("0.\tExit")

# menu = "Please choose your option from the list below:"
# for i in options:
#     menu += "\n{}".format(i)
# print(menu)

# while len(options) != 0:
#     choice = input("Enter the number ")

#     if choice.isnumeric():
#         choice = int(choice)
#         if choice == 0:
#             print("Exiting ...")
#             break
#         elif choice-1 in range(len(options)-1):
#             # print("Today you chose option '{}'. ".format(choice))
#             print("Today you chose '{}'. ".format(options[choice-1]))
#         else:
#             print(menu)


# #TODO Processing SORTED lists for outliers
# data = [4,5,100,104,110,120,130,130,150,160,170,183,185,187,188,191,200,350,360]  # Given Sample
# # data = [4,5,100,104,110,120,130,130,150,160,170,183,185,187,188,191,200]          # No bigger data in sample
# # data = [100,104,110,120,130,130,150,160,170,183,185,187,188,191,200,350,360]      # No smaller data in sample
# # data = [100,104,110,120,130,130,150,160,170,183,185,187,188,191,200]              # All data is valid
# # data = [25796,982164,34156,1346,1346,3157,53648,12345,3856]                       # No data is valid
# # data = []                                                                         # No data given
# min_valid = 100
# max_valid = 200
# print("Original Data\t\t{0}\tData length {1}".format(data,len(data)))
# # processing low values in the SORTED list
# stop = 0
# for index, value in enumerate(data):
#     if value >= min_valid:
#         stop = index
#         break

# # print(stop) # for debugging
# del data[:stop]
# print("No more Smaller Data\t{0}\tData length {1}".format(data,len(data)))


# #TODO processing high values in the SORTED list
# start = 0
# # for index in range(lastPosition - 1 , -1 (We need the first index so no using 0), -1 (go backwards)]):
# for index in range(len(data)-1 , -1 , -1):
#     if data[index] <= max_valid:
#         # index will be the possition of the last valid data
#         start = index + 1
#         # we want to start deleting from the one after
#         break

# # print(start) # for debugging
# del data[start:]
# print("No more Bigger Data\t{0}\tData length {1}".format(data,len(data)))


# #TODO Processing UNsorted lists for outliers
# data = [104,101,4,105,308,103,5,107,100,306,106,102,108]
# min_valid = 100
# max_valid = 200

# # for index in range(len(data)-1,-1,-1):
# #     if data[index] < min_valid or data[index]>max_valid:
# #         print(index,data)
# #         del data[index]
# print(data)

# top = len(data)-1
# for index,value in enumerate(reversed(data)):
#     if value < min_valid or value>max_valid:
#         print(top-index,value)
#         del data[top-index]
# print(data)

# # list.sort() changes list
# # sorted(list) copies into list2 then sorts list2


# #TODO Removing seperators
# numbers = "9,223,372,036,854,755,807"
# digits = []
# for char in numbers.split(","):
#     digits.append(int(char))
# print(digits)


# #TODO Album stuff and Jukebox
# albums = [("Name 1","Artist 1", "Year 1",("A1 Song 1","A1 Song 2","A1 Song 3")),
#           ("Name 2","Artist21", "Year 2",("A2 Song 1","A2 Song 2","A2 Song 3")),
#           ("Name 3","Artist31", "Year 3",("A3 Song 1","A3 Song 2","A3 Song 3")),
#           ("Name 4","Artist41", "Year 4",("A4 Song 1","A4 Song 2","A4 Song 3")),
#           ("Name 5","Artist51", "Year 5",("A5 Song 1","A5 Song 2","A5 Song 3"))
#          ]
# print(len(albums))
# # for album in albums:
# #     (name,artist,year) = album
# #     print("Album: {}, Artist: {}, Year: {}".format(name,artist,year))
# for name,artist,year,song in albums:
#     print("Album: {},\tArtist: {},\tYear: {},\tSong: {}".format(name,artist,year,song))

# albums = [
#     ("Welcome to my Nightmare", "Alice Cooper", 1975,
#      [
#          (1, "Welcome to my Nightmare"),
#          (2, "Devil's Food"),
#          (3, "The Black Widow"),
#          (4, "Some Folks"),
#          (5, "Only Women Bleed"),
#      ]
#      ),
#     ("Bad Company", "Bad Company", 1974,
#      [
#          (1, "Can't Get Enough"),
#          (2, "Rock Steady"),
#          (3, "Ready for Love"),
#          (4, "Don't Let Me Down"),
#          (5, "Bad Company"),
#          (6, "The Way I Choose"),
#          (7, "Movin' On"),
#          (8, "Seagull"),
#      ]
#      ),
#     ("Nightflight", "Budgie", 1981,
#      [
#          (1, "I Turned to Stone"),
#          (2, "Keeping a Rendezvous"),
#          (3, "Reaper of the Glory"),
#          (4, "She Used Me Up"),
#      ]
#      ),
#     ("More Mayhem", "Imelda May", 2011,
#      [
#          (1, "Pulling the Rug"),
#          (2, "Psycho"),
#          (3, "Mayhem"),
#          (4, "Kentish Town Waltz"),
#      ]
#      ),
# ]

# SONGS_LIST_INDEX = 3
# SONG_TITLE_INDEX = 1

# while True:
#     print("Please choose your album (invalid choice exits): ")
#     for index, (title, artist, year, songs) in enumerate(albums):
#         print("{}: {}".format(index + 1, title))

#     choice = int(input())
#     if 1 <= choice <= len(albums):
#         songs_list = albums[choice -1][SONGS_LIST_INDEX]
#     else:
#         break

#     print("Please choose your song: ")
#     for index, (track_number, song) in enumerate(songs_list):
#         print("{}: {}".format(index + 1, song))

#     song_choice = int(input())
#     if 1 <= song_choice <= len(songs_list):
#         title = songs_list[song_choice - 1][SONG_TITLE_INDEX]
    
#     print("Now Playing ... {} ... ".format(title))
#     print("=" * 40)


# #TODO Palindrome


def is_palindrome(string):
    """
    Check if a string is a palindrome.
 
    A palindrome is a string that reads the same forwards as backwards.
 
    :param string: The string to check.
    :return: True if `string` is a palindrome, False otherwise.
    """
    return string[::-1].casefold() == string.casefold()


def palindrome_sentence(string):
    """
    Check if a sentence is a palindrome.
 
    The function ignores everything in the sentence not in the allowed_characters variable.
 
    :param string: The string to check.
    :return: True if `sentence` is a palindrome, False otherwise.
    """
    allowed_characters = "abcdefghijklmnopqrstuvwxyz"
    # allowed_characters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
    # allowed_characters = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",1,2,3,4,5,6,7,8,9,0]
    test_string = ""
    for character in string.casefold():
        if character in allowed_characters:
            test_string+=character
    return is_palindrome(test_string)


data = input("Please enter something to test: ")
if " " in data:
    if palindrome_sentence(data) or is_palindrome(data):
        print("'{}' is a palendrome".format(data))
    else:
        print("'{}' is not a palendrome".format(data))
else:
    if is_palindrome(data):
        print("'{}' is a palendrome".format(data))
    else:
        print("'{}' is not a palendrome".format(data))


# #TODO Function Docstring examples

# import tkinter as tk
# import tkinter.dnd


# # TODO reStructuredText Docstring example
# def dnd_accept(self, source, event):
#     """
#     Decide what object will accept the drop.
    
#     The returned object will become the new target for the drop operation
    
#     :param source: The object being dragged.
#     :param event: The tk event that resulted in this call. Usually a motion event.
#     :return: The object that will accept a drop - this widget.
#     """
#     print("dnd_accept. Called on {}. source is {}, event type is {}".format(self, source, event))
#     return self


# # TODO Google Docstring example
# def on_dnd_start(event):
#     """Starts a drag and drop (dnd) operation.
    
#     This is usually invoked by a mouse event binding on a widget that can be dragged.
    
#     For example, `tile.bind('<ButtonPress>', on_dnd_start)`
    
#     Args:
#         event: The tk event that resulted in this call.
#     Returns:
#         The object to be dragged. Here, it's the widget that was clicked to call this function.
#     """
#     tk.dnd.dnd_start(event.widget, event)


# dnd_accept()
# on_dnd_start()


# def get_integer(prompt):
#     """
#     Get and Integer from Standard Input (stdin).

#     The function will continue looping, and prompting the user, until a valid `int` is entered.

#     :param prompt: The String that the user will see, when they're prompted to enter the value.
#     :return: The integer that the user enters.
#     """
#     while True:
#         temp = input(prompt)
#         if temp.isnumeric():
#             return int(temp)
#         # else:
#         print("{} is not a valid number".format(temp))



# #TODO Banner text across screen
# def banner_text(text=" ",screen_width=20):
#     """
#     Get and Integer from Standard Input (stdin).

#     The function will continue looping, and prompting the user, until a valid `int` is entered.

#     :param prompt: The String that the user will see, when they're prompted to enter the value.
#     :return: The integer that the user enters.
#     """
#     border_width = 2
#     if len(text)>(screen_width - (border_width * 2)):
#         raise ValueError("String {0} ({1}) is larger than specified width {2}".format(text,len(text),screen_width))
#     if text == "*":
#         print("*"*screen_width)
#     else:
#         centered_test = text.center(screen_width - (border_width * 2))
#         output_string = "**{}**".format(centered_test)
#         print(output_string)


# banner_text("*")
# banner_text("Line 1")
# banner_text() # Blank line
# banner_text("Short Ln 1",14)
# banner_text("*")


# #TODO Fibonachi number maker


# def fibonachi(n: int):
#     """
#     Return the \`n\`th Fibonachi number for positive \`n\`.
#     """
#     if 0<=n<=1:
#         return n # No else needed because function will end if true
#     n_minus_1,n_minus_2 = 1,0

#     result = None
#     for f in range(n - 1):
#         result = n_minus_2+n_minus_1
#         n_minus_2 = n_minus_1
#         n_minus_1 = result
#     return result


# for i in range(36):
#     print("{}\t{}".format(i,fibonachi(i)))
```

### Expected behavior

Code should ask for user input and test if it is a palindrome (same text forwards or backwards)

### Actual behavior

Terminal crashes before starting code.
